### PR TITLE
Test the compatibility with pygobject-3.40.1-1

### PR DESCRIPTION
**Pull request by poncovka**

### CODE REVIEW

**Comment by poncovka** [comment]
The tests are failing with the following error:
```
`TypeError: _object_callback() missing 1 required positional argument: 'user_data'`
```

The error is caused by calling the `_object_callback` method below without the `user_data` argument:

```
@classmethod
def _object_callback(cls, connection, sender, object_path,
                     interface_name, method_name, parameters,
                     invocation, user_data):
```

The `user_data` argument should be provided by a [partial object](https://docs.python.org/3/library/functools.html#partial-objects) that is used as a method call closure of the [Gio.DBusConnection.register_object](https://lazka.github.io/pgi-docs/Gio-2.0/classes/DBusConnection.html#Gio.DBusConnection.register_object) call. It looks like the GLib library at some point drops the predefined arguments of the partial object and calls the wrapped function without them. 

```
method_call_closure = partial(
    cls._object_callback,
    user_data=(callback, callback_args)
)

connection.register_object(
    object_path,
    interface_info,
    method_call_closure,
    None,
    None
)
```

**Comment by kalev** [comment]
Could you file this upstream at https://gitlab.gnome.org/GNOME/pygobject please? The folks there should be able to narrow down what has changed and if it was deliberate or not.

**Comment by jkonecny12** [comment]
This bug is also reported upstream: https://bugzilla.redhat.com/show_bug.cgi?id=1944062

**Comment by poncovka** [comment]
Reported to upstream: https://gitlab.gnome.org/GNOME/pygobject/-/issues/464

**Comment by kalev** [comment]
Nice, thanks!

**Comment by poncovka** [comment]
The issue was fixed in `pygobject3-3.40.1-1`.

**Pull request closed without merging**
